project_id = "dxxovxcdbdkyhokusnaz"

[functions.razorpay-webhook]
verify_jwt = false

[functions.razorpay-config]
verify_jwt = true

[functions.chat-openai]
verify_jwt = true

[functions.chat-anthropic]
verify_jwt = true

[functions.chat-google]
verify_jwt = true

[functions.fx-updater]
verify_jwt = false

[functions.fx-trigger]
verify_jwt = false

[functions.chat-stream]
verify_jwt = true